## mk-change-chr-dbSNP ###
# mkfile script with dependency rules for:
#	1. Change chr nomenclature from original dbSNP to human type.
## For more information about 'mk' dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run scripts.
MKSHELL=/bin/bash

%_dbSNP.vcf.gz:Q: %.tmp.gz
	bcftools annotate \
		--rename-chrs $NAMES_CHR \
		--remove INFO \
		$prereq \
		| bgzip > $target.build \
	&& mv $target.build $target \
	&& tabix -p vcf $target

%.tmp.gz:Q: %.gz
	bcftools norm \
		--multiallelics -snps \
		$prereq \
		| bgzip > $target.build \
	&& mv $target.build $target \
	&& tabix -p vcf $target
